
main_weakptr: main_weakptr.cc observer_weakptr.h observable_weakptr.h observer_weakptr.cc observable_weakptr.cc
	g++ main_weakptr.cc observer_weakptr.h observable_weakptr.h observer_weakptr.cc observable_weakptr.cc -o main_weakptr -lpthread