ALL: main_array main_circularqueue

main_array: main_array.cc
	g++ main_array.cc -o main_array -lpthread

main_circularqueue: main_circularqueue.cc
	g++ main_circularqueue.cc -o main_circularqueue -lpthread

clean:
	rm -rf main_array